name: gql

packages:
  - "gql"
  - "codegen/*"
  - "gql_pedantic"
  - "links/*"
  - "examples/*"
ignore:
  - "examples/gql_example_flutter"

categories:
  packages:
    - "gql"
    - "gql_pedantic"
    - "codegen/gql_build"
    - "codegen/gql_code_builder"
    - "codegen/gql_code_builder_serializers"
    - "codegen/gql_tristate_value"
    - "links/gql_exec"
    - "links/gql_link"
    - "links/gql_dedupe_link"
    - "links/gql_dio_link"
    - "links/gql_error_link"
    - "links/gql_http_link"
    - "links/gql_websocket_link"
    - "links/gql_transform_link"
  builders:
    - "codegen/end_to_end_test"
    - "codegen/end_to_end_test_tristate"
  examples:
    - "examples/gql_example_cli"
    - "examples/gql_example_cli_github"
    - "examples/gql_example_build"
    - "examples/gql_example_http_auth_link"
    - "examples/gql_example_dio_link"

scripts:
  test:
    run: dart test
    description: Run tests for the entire monorepo
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
      ignore: "*example*"

  publish:
    description: Publish all packages to pub.dev
    run: melos publish --no-private
    packageFilters:
      ignore:
        - "*example*"
        - "end_to_end_test"
        - "end_to_end_test_tristate"

  version:
    description: Updates versions for all packages
    run: melos version --no-git-tag-version --no-private

  minor-version:
    description: Updates versions for all packages
    run: melos version --minor --no-git-tag-version --no-private

  major-version:
    description: Updates versions for all packages
    run: melos version --major --no-git-tag-version --no-private

  patch-version:
    description: Updates versions for all packages
    run: melos version --patch --no-git-tag-version --no-private

  clean:
    description: Clean all packages
    run: melos clean

  build:
    run: melos exec -c 1 -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all packages with build_runner
    packageFilters:
      dependsOn: build_runner

  bump-alpha:
    description: Bump all packages to next alpha version
    run: |
      melos version --prerelease \
        --preid=alpha \
        --no-git-tag-version \
        --no-private \
        --yes

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false
  version:
    # Makes version command update all dependencies
    updateDependencies: true
    linkToCommits: false

sdkPath: auto
