name: gql

packages:
  - "gql"
  - "codegen/*"
  - "gql_pedantic"
  - "links/*"
  - "examples/*"
ignore:
  - "examples/gql_example_flutter"

scripts:
  test:
    run: dart test
    description: Run tests for the entire monorepo
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
      ignore: "*example*"

  publish:
    description: Publish all packages to pub.dev
    run: melos publish --no-private
    packageFilters:
      ignore:
        - "*example*"
        - "end_to_end_test"
        - "end_to_end_test_tristate"

  version:
    description: Updates versions for all packages
    run: melos version --no-git-tag-version --no-private

  clean:
    description: Clean all packages
    run: melos clean

  build:
    run: melos exec -c 1 -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all packages with build_runner
    packageFilters:
      dependsOn: build_runner

  bump-alpha:
    description: Bump all packages to next alpha version
    run: |
      melos version --prerelease \
        --preid=alpha \
        --no-git-tag-version \
        --yes

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false
  version:
    # Makes version command update all dependencies
    updateDependencies: true
    linkToCommits: false

sdkPath: auto
