name: Publish Release
on:
  push:
    branches:
      - release
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: dart:latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install melos
        run: dart pub get
      - name: Bootstrap workspace
        run: dart run melos bootstrap --no-flutter
      - name: Validate packages
        run: dart run melos format && dart run melos analyze && dart run melos test
      - name: Publish packages
        env:
          PUB_CREDENTIALS_JSON: ${{ secrets.PUB_CREDENTIALS_JSON }}
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart/
          echo $PUB_CREDENTIALS_JSON > $XDG_CONFIG_HOME/dart/pub-credentials.json
          mkdir -p $HOME/.config/dart/
          echo $PUB_CREDENTIALS_JSON > $HOME/.config/dart/pub-credentials.json
          dart run melos publish --no-dry-run --yes
